name: Update data

concurrency:
  group: update-data
  cancel-in-progress: true

on:
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    env:
      GH_AUTH_TOKEN: ${{ secrets.GH_AUTH_TOKEN }}
      GH_REPO_OWNER: ${{ secrets.GH_REPO_OWNER }}
      GH_REPO_NAME: ${{ secrets.GH_REPO_NAME }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn

      - name: Load workflows
        run: yarn analytics load workflows

      - name: Check loaded files
        run: find data/$GH_REPO_OWNER/$GH_REPO_NAME
