name: Update data

concurrency:
  group: update-data
  cancel-in-progress: true

on:
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    env:
      GH_AUTH_TOKEN: ${{ secrets.GH_AUTH_TOKEN }}
      GH_REPO_OWNER: ${{ secrets.GH_REPO_OWNER }}
      GH_REPO_NAME: ${{ secrets.GH_REPO_NAME }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn

      - name: Load workflows
        run: yarn analytics load workflows --from=2023-08-02 --to=2023-08-09

      - name: Load workflow runs
        run: yarn analytics load workflow_runs --from=2023-08-02 --to=2023-08-09

      - name: Report workflow runs
        run: yarn analytics report workflow_runs --from=2023-08-02 --to=2023-08-09

      - name: Merge workflow runs reports
        run: yarn analytics merge_reports workflow_runs --from=2023-08-02 --to=2023-08-09

      - name: Check loaded files
        run: find data/$GH_REPO_OWNER/$GH_REPO_NAME

      - name: Commit changes
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "Update data"
          git push
