name: Update data

concurrency:
  group: update-data
  cancel-in-progress: true

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'

env:
  GH_AUTH_TOKEN: ${{ matrix.repos.token }}

jobs:
  update-data:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        repos:
          - owner: DevExpress
          - name: DevExtreme
          - token: ${{ env.GH_AUTH_TOKEN }}

    env:
      GH_AUTH_TOKEN: ${{ matrix.repos.token }}
      GH_REPO_OWNER: ${{ matrix.repos.owner }}
      GH_REPO_NAME: ${{ matrix.repos.name }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn

      - name: Build workflow runs report
        run: yarn analytics report workflow_runs_last_days --days=16 --fetch

      - name: Build jobs report
        run: yarn analytics report jobs_last_days --days=7 --fetch

      - name: Build a list of failures
        run: yarn analytics report failures_last_days --days=7 --delimiter=';' --fetch

      - name: Commit changes
        if: always()
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "Update data"
          git push
