name: Update data

concurrency:
  group: update-data
  cancel-in-progress: true

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'

jobs:
  update-data:
    runs-on: ubuntu-latest

    name: ${{ matrix.repos.owner }}/${{ matrix.repos.name }}

    strategy:
      max-parallel: 1
      matrix:
        repos:
          - owner: DevExpress
            name: DevExtreme
          - owner: DevExpress
            name: devextreme-demos

    env:
      GH_REPO_OWNER: ${{ matrix.repos.owner }}
      GH_REPO_NAME: ${{ matrix.repos.name }}
      GH_AUTH_TOKEN: ${{ secrets.GH_AUTH_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn

      - name: Build workflow runs report
        run: yarn analytics report workflow_runs_last_days --days=16 --fetch

      - name: Build jobs report
        run: yarn analytics report jobs_last_days --days=7 --fetch

      - name: Build a list of failures
        run: yarn analytics report failures_last_days --days=7 --delimiter=';' --fetch

      - name: Commit changes
        if: always()
        continue-on-error: true
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git pull
          git add .
          git commit -m "Update ${{ matrix.repos.owner }}/${{ matrix.repos.name }} data"
          git push
