name: Update data

concurrency:
  group: update-data
  cancel-in-progress: true

on:
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    env:
      GH_AUTH_TOKEN: ${{ secrets.GH_AUTH_TOKEN }}
      GH_REPO_OWNER: ${{ secrets.GH_REPO_OWNER }}
      GH_REPO_NAME: ${{ secrets.GH_REPO_NAME }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn

      - name: Build workflow runs report
        run: yarn analytics report workflow_runs_last_days --days=16 --fetch

      - name: Build jobs report
        run: yarn analytics report jobs_last_days --days=1 --fetch

      - name: Commit changes
        if: always()
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "Update data"
          git push
