name: Upload file to maven
 
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
        type: string
 
jobs:
  upload:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Create test VSIX
        run: |
          echo "Test VSIX content - $(date)" > test-extension-${{ inputs.version }}.vsix
      - name: Publish package
        shell: pwsh
        run: |
          .\upload-to-github-packages-maven.ps1 `
            -Owner "${{ github.repository_owner }}" `
            -Repo "${{ github.event.repository.name }}" `
            -PackageName "test-extension" `
            -Version "${{ inputs.version }}" `
            -FilePath "test-extension-${{ inputs.version }}.vsix" `
            -GithubToken "${{ secrets.GITHUB_TOKEN }}" `
            -ScopeType "users"
            # -Force
