name: Upload file to maven
 
on:
  workflow_dispatch:
 
jobs:
  upload:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Create test VSIX
        run: |
          echo "Test VSIX content - $(date)" > test-extension-1.0.0.vsix
      - name: Upload to GitHub Packages
        shell: pwsh
        run: |
          $token = "${{ secrets.GITHUB_TOKEN }}"
          $repo = "${{ github.repository }}"
          $file = "test-extension-1.0.0.vsix"
          $url = "https://maven.pkg.github.com/$repo/test-extension/1.0.0/$file"

          try {
            $response = Invoke-RestMethod `
              -Uri $url `
              -Method Put `
              -Headers @{
                "Authorization" = "Bearer $token"
                "Content-Type"  = "application/octet-stream"
              } `
              -InFile $file `
              -ErrorAction Stop

            Write-Host "✅ Successfully uploaded to GitHub Packages!"
          } catch {
            Write-Host "❌ Upload failed:"
            Write-Host $_.Exception.Message
            if ($_.ErrorDetails.Message) { Write-Host $_.ErrorDetails.Message }
            exit 1
          }
      - name: Verify upload
        run: |
          echo "✅ Package uploaded!"
          echo "View at: https://github.com/${{ github.repository_owner }}?tab=packages"
